### Step 1 : Importing Libraries

In [31]:
import pandas as pd 
import numpy as np

### Step 2 : Load Dataset

In [32]:
df=pd.read_excel("C:/data_science/Projects/cloud_sales_analysis/data/raw/sales_data_raw_with_transformation.xlsx")

### Step 3 : Understanding the Data

In [35]:
df.shape

(10194, 17)

In [36]:
df.head()   # First Five Rows

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,product_id,category,sub_category,order_priority,product_name,sales,quantity,discount,profit
0,1,US-2020-103800,2020-01-03,2020-01-07,Standard Class,DP-13000,Darren Powers,Consumer,OFF-PA-10000174,Office Supplies,Paper,High,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2020-112326,2020-01-04,2020-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,OFF-BI-10004094,Office Supplies,Binders,Low,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2020-112326,2020-01-04,2020-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,OFF-LA-10003223,Office Supplies,Labels,High,Avery 508,11.784,3,0.2,4.2717
3,4,US-2020-112326,2020-01-04,2020-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,OFF-ST-10002743,Office Supplies,Storage,Low,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2020-141817,2020-01-05,2020-01-12,Standard Class,MB-18085,Mick Brown,Consumer,OFF-AR-10003478,Office Supplies,Art,High,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [37]:
df.tail()  # Last 5 Rows

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,product_id,category,sub_category,order_priority,product_name,sales,quantity,discount,profit
10189,10190,US-2023-143259,2023-12-30,2024-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,OFF-BI-10003684,Office Supplies,Binders,Low,Wilson Jones Legal Size Ring Binders,52.776,3,0.2,19.7910
10190,10191,US-2023-115427,2023-12-30,2024-01-03,Standard Class,EB-13975,Erica Bern,Corporate,OFF-BI-10004632,Office Supplies,Binders,Low,GBC Binding covers,20.720,2,0.2,6.4750
10191,10192,US-2023-156720,2023-12-30,2024-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,OFF-FA-10003472,Office Supplies,Fasteners,Medium,Bagged Rubber Bands,3.024,3,0.2,-0.6048
10192,10193,US-2023-143259,2023-12-30,2024-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,TEC-PH-10004774,Technology,Phones,High,Gear Head AU3700S Headset,90.930,7,0.0,2.7279
10193,10194,CA-2023-143500,2023-12-30,2024-01-03,Standard Class,HO-15230,Harry Olson,Consumer,OFF-BI-10004040,Office Supplies,Binders,High,Wilson Jones Impact Binders,3.024,3,0.2,-0.6048

In [38]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'product_id', 'category',
       'sub_category', 'order_priority', 'product_name', 'sales', 'quantity',
       'discount', 'profit'],
      dtype='object')

In [39]:
df.describe()

,Row ID,Order Date,Ship Date,sales,quantity,discount,profit
count,10194.000000,10194,10194,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,2022-04-29 16:37:51.453796608,2022-05-03 15:41:38.175397120,228.225854,3.791838,0.155385,28.673417
min,1.000000,2020-01-03 00:00:00,2020-01-07 00:00:00,0.444000,1.000000,0.000000,-6599.978000
25%,2549.250000,2021-05-14 00:00:00,2021-05-19 00:00:00,17.220000,2.000000,0.000000,1.760800
50%,5097.500000,2022-06-25 00:00:00,2022-06-28 00:00:00,53.910000,3.000000,0.200000,8.690000
75%,7645.750000,2023-05-14 00:00:00,2023-05-18 00:00:00,209.500000,5.000000,0.200000,29.297925
max,10194.000000,2023-12-30 00:00:00,2024-01-05 00:00:00,22638.480000,14.000000,0.800000,8399.976000
std,2942.898656,NaN,NaN,619.906839,2.228317,0.206249,232.465115

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  datetime64[ns]
 3   Ship Date       10194 non-null  datetime64[ns]
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  object
 6   Customer Name   10194 non-null  object
 7   Segment         10194 non-null  object
 8   product_id      10194 non-null  object
 9   category        10194 non-null  object
 10  sub_category    10194 non-null  object
 11  order_priority  10194 non-null  object
 12  product_name    10194 non-null  object
 13  sales           10194 non-null  float64
 14  quantity        10194 non-null  int64
 15  discount        10194 non-null  float64
 16  profit          10194 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(10)
memory usage: 1.3+ MB

### Step 4 : Clean Column Names

In [41]:
df.columns=df.columns.str.strip().str.lower().str.replace(" ","_")
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'product_id', 'category',
       'sub_category', 'order_priority', 'product_name', 'sales', 'quantity',
       'discount', 'profit'],
      dtype='object')

In [42]:
df[['order_date','ship_date']].head()

  order_date  ship_date
0 2020-01-03 2020-01-07
1 2020-01-04 2020-01-08
2 2020-01-04 2020-01-08
3 2020-01-04 2020-01-08
4 2020-01-05 2020-01-12

### Step 5 : Handling Missing Values and duplicates

In [43]:
df.isnull().sum()

row_id            0
order_id          0
order_date        0
ship_date         0
ship_mode         0
customer_id       0
customer_name     0
segment           0
product_id        0
category          0
sub_category      0
order_priority    0
product_name      0
sales             0
quantity          0
discount          0
profit            0
dtype: int64

In [44]:
df.duplicated().sum()

0

### Step 6 : Features Engineering

In [45]:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_quarter'] = df['order_date'].dt.quarter

df['delivery_days'] = (df['ship_date'] - df['order_date']).dt.days

In [46]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,product_id,category,...,order_priority,product_name,sales,quantity,discount,profit,order_year,order_month,order_quarter,delivery_days
0,1,US-2020-103800,2020-01-03,2020-01-07,Standard Class,DP-13000,Darren Powers,Consumer,OFF-PA-10000174,Office Supplies,...,High,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,2020,1,1,4
1,2,US-2020-112326,2020-01-04,2020-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,OFF-BI-10004094,Office Supplies,...,Low,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,2020,1,1,4
2,3,US-2020-112326,2020-01-04,2020-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,OFF-LA-10003223,Office Supplies,...,High,Avery 508,11.784,3,0.2,4.2717,2020,1,1,4
3,4,US-2020-112326,2020-01-04,2020-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,OFF-ST-10002743,Office Supplies,...,Low,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,2020,1,1,4
4,5,US-2020-141817,2020-01-05,2020-01-12,Standard Class,MB-18085,Mick Brown,Consumer,OFF-AR-10003478,Office Supplies,...,High,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,2020,1,1,7

### Step 7 : Saved the cleaned file

In [47]:
df.to_csv('C:/data_science/Projects/cloud_sales_analysis/data/cleaned/sales_cleaned.csv', index=False)

# Data Modeling

### Step 1 : Load clean data

In [48]:
df=pd.read_csv('C:/data_science/Projects/cloud_sales_analysis/data/cleaned/sales_cleaned.csv')

In [49]:
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,product_id,category,...,order_priority,product_name,sales,quantity,discount,profit,order_year,order_month,order_quarter,delivery_days
0,1,US-2020-103800,2020-01-03,2020-01-07,Standard Class,DP-13000,Darren Powers,Consumer,OFF-PA-10000174,Office Supplies,...,High,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,2020,1,1,4
1,2,US-2020-112326,2020-01-04,2020-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,OFF-BI-10004094,Office Supplies,...,Low,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870,2020,1,1,4
2,3,US-2020-112326,2020-01-04,2020-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,OFF-LA-10003223,Office Supplies,...,High,Avery 508,11.784,3,0.2,4.2717,2020,1,1,4
3,4,US-2020-112326,2020-01-04,2020-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,OFF-ST-10002743,Office Supplies,...,Low,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748,2020,1,1,4
4,5,US-2020-141817,2020-01-05,2020-01-12,Standard Class,MB-18085,Mick Brown,Consumer,OFF-AR-10003478,Office Supplies,...,High,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,2020,1,1,7

### Step 2 : Create a dimension table

In [50]:
# dim_customer
dim_customer = df[['customer_id', 'customer_name', 'segment']].drop_duplicates()
dim_customer.head()

  customer_id  customer_name      segment
0    DP-13000  Darren Powers     Consumer
1    PO-19195  Phillina Ober  Home Office
4    MB-18085     Mick Brown     Consumer
5    ME-17320  Maria Etezadi  Home Office
7    JO-15145  Jack O'Briant    Corporate

In [51]:
# dim_product 
dim_product = df[['product_id', 'product_name', 'category', 'sub_category']].drop_duplicates()
dim_product

,product_id,product_name,category,sub_category
0,OFF-PA-10000174,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Office Supplies,Paper
1,OFF-BI-10004094,GBC Standard Plastic Binding Systems Combs,Office Supplies,Binders
2,OFF-LA-10003223,Avery 508,Office Supplies,Labels
3,OFF-ST-10002743,SAFCO Boltless Steel Shelving,Office Supplies,Storage
4,OFF-AR-10003478,Avery Hi-Liter EverBold Pen Style Fluorescent ...,Office Supplies,Art
...,...,...,...,...
9510,OFF-PA-10002558,Xerox 1938,Office Supplies,Paper
9561,OFF-PA-10000308,Xerox 1901,Office Supplies,Paper
9710,TEC-PH-10001468,Panasonic Business Telephones KX-T7736,Technology,Phones
9820,TEC-MA-10001856,Okidata C610n Printer,Technology,Machines
10023,FUR-BO-10002206,"Bush Saratoga Collection 5-Shelf Bookcase, Han...",Furniture,Bookcases

In [52]:
# dim_date
dim_date = df[['order_date']].drop_duplicates()

dim_date['year'] = pd.to_datetime(dim_date['order_date']).dt.year
dim_date['month'] = pd.to_datetime(dim_date['order_date']).dt.month
dim_date['quarter'] = pd.to_datetime(dim_date['order_date']).dt.quarter
dim_date

       order_date  year  month  quarter
0      2020-01-03  2020      1        1
1      2020-01-04  2020      1        1
4      2020-01-05  2020      1        1
5      2020-01-06  2020      1        1
14     2020-01-07  2020      1        1
...           ...   ...    ...      ...
10146  2023-12-26  2023     12        4
10150  2023-12-27  2023     12        4
10152  2023-12-28  2023     12        4
10171  2023-12-29  2023     12        4
10186  2023-12-30  2023     12        4

[1242 rows x 4 columns]

### Step 3 : Create fact table

In [53]:
# fact_sales
fact_sales = df[['order_id', 'product_id', 'customer_id',
                 'order_date', 'ship_date',
                 'sales', 'quantity', 'discount', 'profit']]
fact_sales

,order_id,product_id,customer_id,order_date,ship_date,sales,quantity,discount,profit
0,US-2020-103800,OFF-PA-10000174,DP-13000,2020-01-03,2020-01-07,16.448,2,0.2,5.5512
1,US-2020-112326,OFF-BI-10004094,PO-19195,2020-01-04,2020-01-08,3.540,2,0.8,-5.4870
2,US-2020-112326,OFF-LA-10003223,PO-19195,2020-01-04,2020-01-08,11.784,3,0.2,4.2717
3,US-2020-112326,OFF-ST-10002743,PO-19195,2020-01-04,2020-01-08,272.736,3,0.2,-64.7748
4,US-2020-141817,OFF-AR-10003478,MB-18085,2020-01-05,2020-01-12,19.536,3,0.2,4.8840
...,...,...,...,...,...,...,...,...,...
10189,US-2023-143259,OFF-BI-10003684,PO-18865,2023-12-30,2024-01-03,52.776,3,0.2,19.7910
10190,US-2023-115427,OFF-BI-10004632,EB-13975,2023-12-30,2024-01-03,20.720,2,0.2,6.4750
10191,US-2023-156720,OFF-FA-10003472,JM-15580,2023-12-30,2024-01-03,3.024,3,0.2,-0.6048
10192,US-2023-143259,TEC-PH-10004774,PO-18865,2023-12-30,2024-01-03,90.930,7,0.0,2.7279
10193,CA-2023-143500,OFF-BI-10004040,HO-15230,2023-12-30,2024-01-03,3.024,3,0.2,-0.6048

In [54]:
dim_customer.to_csv('C:/data_science/Projects/cloud_sales_analysis/data/cleaned/dim_customer.csv', index=False)
dim_product.to_csv('C:/data_science/Projects/cloud_sales_analysis/data/cleaned/dim_product.csv', index=False)
dim_date.to_csv('C:/data_science/Projects/cloud_sales_analysis/data/cleaned/dim_date.csv', index=False)
fact_sales.to_csv('C:/data_science/Projects/cloud_sales_analysis/data/cleaned/fact_sales.csv', index=False)

### Step 4 : import data in Mysql

In [59]:
import pandas as pd
from sqlalchemy import create_engine

# Step 1: Load CSV
df = pd.read_csv('C:/data_science/Projects/cloud_sales_analysis/data/cleaned/dim_product.csv')

# Step 2: Clean column names (important)
df.columns = df.columns.str.strip()

# Step 3: MySQL connection (password encoded)
engine = create_engine("mysql+pymysql://root:Rajesh%40123@localhost:3306/sales_project")

# Step 4: Load into MySQL
df.to_sql(name="dim_product", con=engine, if_exists="replace", index=False)

print("Data loaded successfully 🚀")

Data loaded successfully 🚀